# Generated by Django 4.2.21 on 2025-06-09 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('command_type', models.CharField(max_length=100)),
                ('command_params', models.JSONField(default=dict)),
                ('user_id', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100)),
                ('api_config_id', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(default=dict)),
                ('execution_time', models.FloatField()),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('command_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.commandrequest')),
            ],
        ),
    ]
