# Generated by Django 4.2.21 on 2025-05-28 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('protocol', models.CharField(choices=[('http', 'HTTP/HTTPS'), ('mqtt', 'MQTT'), ('tcp', 'TCP'), ('websocket', 'WebSocket')], max_length=20)),
                ('base_url', models.CharField(max_length=500)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('oauth2', 'OAuth 2.0')], max_length=20)),
                ('auth_config', models.JSONField(default=dict)),
                ('headers_template', models.JSONField(default=dict)),
                ('request_template', models.JSONField(default=dict)),
                ('command_mappings', models.JSONField(default=dict)),
                ('response_mapping', models.JSONField(default=dict)),
                ('success_indicators', models.JSONField(default=list)),
                ('error_indicators', models.JSONField(default=list)),
                ('timeout', models.IntegerField(default=30)),
                ('retry_count', models.IntegerField(default=3)),
                ('retry_delay', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'db_table': 'api_configurations',
                'unique_together': {('vendor', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url_template', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='POST', max_length=10)),
                ('headers_template', models.JSONField(default=dict)),
                ('body_template', models.JSONField(default=dict)),
                ('required_params', models.JSONField(default=list)),
                ('optional_params', models.JSONField(default=list)),
                ('response_path', models.CharField(blank=True, max_length=200)),
                ('success_condition', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_config.apiconfiguration')),
            ],
            options={
                'db_table': 'command_templates',
                'unique_together': {('api_config', 'command_type')},
            },
        ),
    ]
