# Generated by Django 4.2.21 on 2025-06-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('api_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
