# Generated by Django 4.2.21 on 2025-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0002_alter_apiconfiguration_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='command_mappings',
        ),
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='error_indicators',
        ),
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='response_mapping',
        ),
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='success_indicators',
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], max_length=20),
        ),
    ]
