# Generated by Django 4.2.21 on 2025-06-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0003_remove_apiconfiguration_command_mappings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='request_template',
        ),
    ]
