# Generated by Django 4.2.21 on 2025-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0004_remove_apiconfiguration_request_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP/HTTPS'), ('mqtt', 'MQTT')], max_length=20),
        ),
    ]
