# Generated by Django 4.2.21 on 2025-06-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0005_alter_apiconfiguration_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='host',
        ),
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='port',
        ),
        migrations.RemoveField(
            model_name='apiconfiguration',
            name='protocol',
        ),
    ]
