# Generated by Django 4.2.21 on 2025-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0006_remove_apiconfiguration_host_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfiguration',
            options={'ordering': ['-created_at']},
        ),
    ]
