# Generated by Django 4.2.21 on 2025-06-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0007_alter_apiconfiguration_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandtemplate',
            old_name='display_name',
            new_name='name',
        ),
    ]
