# Generated by Django 4.2.21 on 2025-06-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0008_rename_display_name_commandtemplate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandtemplate',
            name='response_path',
        ),
        migrations.RemoveField(
            model_name='commandtemplate',
            name='success_condition',
        ),
    ]
