# Generated by Django 4.2.21 on 2025-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0009_remove_commandtemplate_response_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandtemplate',
            name='url_template',
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='retry_count',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='retry_delay',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='timeout',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='headers_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='retry_count',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='retry_delay',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='apiconfiguration',
            name='timeout',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='commandtemplate',
            name='headers_template',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
