# Generated by Django 4.2.21 on 2025-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0010_remove_commandtemplate_url_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtemplate',
            name='url_template',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
