# Generated by Django 4.2.21 on 2025-06-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0011_commandtemplate_url_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandtemplate',
            name='api_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_config.apiconfiguration'),
        ),
    ]
