# Generated by Django 4.2.21 on 2025-06-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0012_alter_commandtemplate_api_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfiguration',
            options={'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commandtemplate',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='deleted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='deleted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
