# Generated by Django 4.2.21 on 2025-06-06 09:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_config', '0009_remove_commandtemplate_response_path_and_more'),
        ('vendor', '0002_alter_vendor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict, null=True)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('api_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api_config.apiconfiguration')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vendor.vendor')),
            ],
        ),
    ]
