# Generated by Django 4.2.21 on 2025-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='body',
            new_name='body_template',
        ),
        migrations.RemoveField(
            model_name='device',
            name='headers',
        ),
        migrations.AddField(
            model_name='device',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Authentication'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='headers_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='retry_count',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='retry_delay',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='timeout',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
