# Generated by Django 4.2.21 on 2025-06-06 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0011_commandtemplate_url_template'),
        ('vendor', '0003_alter_vendor_code_alter_vendor_unique_together'),
        ('device', '0002_rename_body_device_body_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='device',
            name='params_template',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('vendor', 'serial_number')},
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.RemoveField(
            model_name='device',
            name='api_config',
        ),
        migrations.CreateModel(
            name='DeviceCommandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('timeout', models.IntegerField(blank=True, default=30, null=True)),
                ('retry_count', models.IntegerField(blank=True, default=3, null=True)),
                ('retry_delay', models.IntegerField(blank=True, default=5, null=True)),
                ('headers_template', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_command_templates', to='api_config.commandtemplate')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_templates', to='device.device')),
            ],
            options={
                'db_table': 'device_command_templates',
                'unique_together': {('device', 'command')},
            },
        ),
    ]
