# Generated by Django 4.2.21 on 2025-06-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_options_device_params_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommandtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
