# Generated by Django 4.2.21 on 2025-06-09 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_config', '0013_alter_apiconfiguration_options_and_more'),
        ('device', '0004_devicecommandtemplate_is_active_alter_device_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('timeout', models.IntegerField(blank=True, default=30, null=True)),
                ('retry_count', models.IntegerField(blank=True, default=3, null=True)),
                ('retry_delay', models.IntegerField(blank=True, default=5, null=True)),
                ('headers_template', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('command_type', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_command', to='api_config.commandtemplate')),
            ],
            options={
                'db_table': 'device_command',
                'ordering': ['priority', '-created_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='device',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='deleted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='DeviceCommandTemplate',
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_templates', to='device.device'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'command_type', 'priority'], name='device_comm_device__390220_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['command_type'], name='device_comm_command_6dd3db_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['is_primary', 'is_active'], name='device_comm_is_prim_ef62b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecommand',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False), ('is_primary', True)), fields=('device', 'command_type'), name='unique_primary_device_command'),
        ),
    ]
