# Generated by Django 4.2.21 on 2025-06-05 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('api_response_time', 'API Response Time'), ('command_success_rate', 'Command Success Rate'), ('user_activity', 'User Activity'), ('system_health', 'System Health'), ('error_rate', 'Error Rate')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('source_service', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='system_metr_metric__ef2754_idx'), models.Index(fields=['source_service'], name='system_metr_source__090b16_idx'), models.Index(fields=['timestamp'], name='system_metr_timesta_206ca6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('user', 'User Events'), ('vendor', 'Vendor Events'), ('api_config', 'API Configuration Events'), ('command', 'Command Events'), ('system', 'System Events'), ('audit', 'Audit Events')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('source_service', models.CharField(max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_timestamp', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_logs',
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['category', 'event_type'], name='event_logs_categor_1e3729_idx'), models.Index(fields=['event_timestamp'], name='event_logs_event_t_2fed6b_idx'), models.Index(fields=['user_id'], name='event_logs_user_id_076f7a_idx'), models.Index(fields=['organization_id'], name='event_logs_organiz_92ab23_idx'), models.Index(fields=['severity'], name='event_logs_severit_180529_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('command_type', models.CharField(max_length=100)),
                ('command_params', models.JSONField(default=dict)),
                ('api_config_id', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'command_execution_logs',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['device_id'], name='command_exe_device__8da5af_idx'), models.Index(fields=['status'], name='command_exe_status_cff907_idx'), models.Index(fields=['requested_at'], name='command_exe_request_df1a2b_idx'), models.Index(fields=['user_id'], name='command_exe_user_id_40e75b_idx'), models.Index(fields=['api_config_id'], name='command_exe_api_con_9bbf8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('login', 'Login'), ('logout', 'Logout'), ('access', 'Access')], max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'resource_type'], name='audit_logs_action_fe069e_idx'), models.Index(fields=['user_id'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
    ]
